web:
  image: kobotoolbox/base-nginx
  links:
    - enketo
  ports:
    - "80:80"
    - "443:443"
  volumes:
    - ./setup/docker/nginx_site_http.conf:/tmp/nginx_site_http.conf
    - ./setup/docker/nginx_site_https.conf:/tmp/nginx_site_https.conf
    - ./setup/docker/secrets/:/tmp/secrets/
    - ./setup/docker/setup_nginx.bash:/etc/my_init.d/setup_nginx.bash
  hostname: ${SSL_HOSTNAME}

enketo-express:
  image: kobotoolbox/enketo-express
  # build: .
  links:
    - redis_main
    - redis_cache
  env_file:
    - ./setup/docker/envfile.txt

redis_main:
  image: redis:2.6
  # Map our "main" Redis config into the container.
  volumes:
    - ./setup/redis/conf/redis-enketo-main.conf:/etc/redis/redis.conf
    - ./setup/docker/redis_main_data/:/data/

redis_cache:
  image: redis:2.6
  # Map our "cache" Redis config into the container.
  volumes:
    - ./setup/redis/conf/redis-enketo-cache.conf:/etc/redis/redis.conf
