nginx:
  image: nginx
  links:
    - enketo_express
  ports:
    - "80:80"
    - "443:443"
  env_file:
    - ./setup/docker/envfile.txt
  volumes:
    - ./setup/docker/nginx/:/tmp/enketo_express_nginx/:ro
    - ./setup/docker/secrets/:/tmp/enketo_express_secrets/:ro
  hostname: ${SSL_HOSTNAME}
  command: bash /tmp/enketo_express_nginx/nginx_command.bash
  restart: always

enketo_express:
  image: kobotoolbox/enketo_express
  # build: .
  links:
    - redis_main
    - redis_cache
  env_file:
    - ./setup/docker/envfile.txt
  volumes:
    - ./setup/docker/secrets/:/srv/src/enketo_express/setup/docker/secrets/
  restart: always

redis_main:
  image: redis:2.6
  # Map our "main" Redis config into the container.
  volumes:
    - ./setup/redis/conf/redis-enketo-main.conf:/etc/redis/redis.conf:ro
    - ./setup/docker/redis_main_data/:/data/
  restart: always

redis_cache:
  image: redis:2.6
  # Map our "cache" Redis config into the container.
  volumes:
    - ./setup/redis/conf/redis-enketo-cache.conf:/etc/redis/redis.conf:ro
  restart: always
